/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Cio;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class TelaConfirmacaoDeCio extends javax.swing.JFrame {

    int aux_inclu = 0;
    int aux_altera = 0;
    int aux_excluir = 0;

    /**
     * Creates new form TelaCadastroBovino
     */
    public TelaConfirmacaoDeCio() {
        initComponents();
        this.desabilitaCampos();
        this.limpaCampos();
        this.desabilitaCampos();
        this.codVacaD.setEditable(false);
        this.nomeVacaD.setEditable(false);
        this.codTouroD.setEditable(false);
        this.nomeTouroD.setEditable(false);
        this.dataCioD.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarU = new javax.swing.JButton();
        inclusaoU = new javax.swing.JButton();
        salvarU = new javax.swing.JButton();
        limparU = new javax.swing.JButton();
        cancelarU = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsD = new javax.swing.JTextPane();
        dataConfirmacaoL = new javax.swing.JLabel();
        dataConfirmacaoD = new com.toedter.calendar.JDateChooser();
        codCioL = new javax.swing.JLabel();
        obsL = new javax.swing.JLabel();
        confirmadoS = new javax.swing.JCheckBox();
        pesquisaCio = new javax.swing.JButton();
        codCioD = new javax.swing.JTextField();
        PainelExebicaodeCio = new javax.swing.JPanel();
        dataCioD = new com.toedter.calendar.JDateChooser();
        dataCioL = new javax.swing.JLabel();
        nomeTouroD = new javax.swing.JTextField();
        codTouroL = new javax.swing.JLabel();
        codVacaD = new javax.swing.JTextField();
        codVacaL = new javax.swing.JLabel();
        codTouroD = new javax.swing.JTextField();
        nomeVacaD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alterarU.setText("Alterar");
        alterarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alterarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUActionPerformed(evt);
            }
        });
        getContentPane().add(alterarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, 21));

        inclusaoU.setText("Incluir");
        inclusaoU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inclusaoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclusaoUActionPerformed(evt);
            }
        });
        getContentPane().add(inclusaoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 90, -1));

        salvarU.setText("Salvar");
        salvarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salvarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarUActionPerformed(evt);
            }
        });
        getContentPane().add(salvarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 90, -1));

        limparU.setText("Limpar");
        limparU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limparU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparUActionPerformed(evt);
            }
        });
        getContentPane().add(limparU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 90, -1));

        cancelarU.setText("Cancelar");
        cancelarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 90, -1));

        jScrollPane1.setViewportView(obsD);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 216, 290, 40));

        dataConfirmacaoL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataConfirmacaoL.setText("Data de Con.:");
        getContentPane().add(dataConfirmacaoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 177, -1, 25));
        getContentPane().add(dataConfirmacaoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 177, 190, 25));

        codCioL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codCioL.setText("Cod. Cio:");
        getContentPane().add(codCioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 25));

        obsL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        obsL.setText("Obs.:");
        getContentPane().add(obsL, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 216, -1, 25));

        confirmadoS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmadoS.setText("Confirmado");
        confirmadoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmadoSActionPerformed(evt);
            }
        });
        getContentPane().add(confirmadoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 25));

        pesquisaCio.setText("pesquisa");
        pesquisaCio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaCioActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisaCio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, -1));

        codCioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codCioDActionPerformed(evt);
            }
        });
        getContentPane().add(codCioD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 83, 25));

        PainelExebicaodeCio.setBackground(new java.awt.Color(204, 204, 204));

        dataCioL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataCioL.setText("Data Do Cio");

        codTouroL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codTouroL.setText("Cod. Touro:");

        codVacaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codVacaDActionPerformed(evt);
            }
        });

        codVacaL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codVacaL.setText("Cod. Vaca:");

        codTouroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTouroDActionPerformed(evt);
            }
        });

        nomeVacaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeVacaDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelExebicaodeCioLayout = new javax.swing.GroupLayout(PainelExebicaodeCio);
        PainelExebicaodeCio.setLayout(PainelExebicaodeCioLayout);
        PainelExebicaodeCioLayout.setHorizontalGroup(
            PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelExebicaodeCioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codVacaL)
                    .addComponent(codTouroL)
                    .addComponent(dataCioL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelExebicaodeCioLayout.createSequentialGroup()
                        .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codTouroD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codVacaD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeVacaD, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(nomeTouroD)))
                    .addComponent(dataCioD, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelExebicaodeCioLayout.setVerticalGroup(
            PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelExebicaodeCioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeVacaD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codVacaD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codVacaL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codTouroL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codTouroD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTouroD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelExebicaodeCioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataCioD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataCioL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PainelExebicaodeCio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUActionPerformed
        this.limpaCampos();
      
    }//GEN-LAST:event_alterarUActionPerformed

    private void salvarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarUActionPerformed
     
        
    }//GEN-LAST:event_salvarUActionPerformed
    public void limpaCampos() {

        this.codCioD.setText("");
        this.codVacaD.setText("");
        this.codTouroD.setText("");
        this.confirmadoS.setSelected(false);
        this.dataCioD.setDate(null);
        this.dataConfirmacaoD.setDate(null);
        this.nomeTouroD.setText("");
        this.nomeVacaD.setText("");
        this.obsD.setText("");
    }

    public void desabilitaCampos() {
        this.codVacaD.setEnabled(false);
        this.pesquisaCio.setEnabled(false);
        this.codCioD.setEnabled(false);
        this.codTouroD.setEnabled(false);
        this.confirmadoS.setEnabled(false);
        this.dataCioD.setEnabled(false);
        this.dataConfirmacaoD.setEnabled(false);
        this.nomeTouroD.setEnabled(false);
        this.nomeVacaD.setEnabled(false);
        this.obsD.setEnabled(false);
        this.limparU.setEnabled(false);
        this.cancelarU.setEnabled(false);
        this.salvarU.setEnabled(false);
    }

    public void habilitaCampos() {
        this.codVacaD.setEnabled(true);
        this.pesquisaCio.setEnabled(true);
        this.codCioD.setEnabled(true);
        this.codTouroD.setEnabled(true);
        this.confirmadoS.setEnabled(true);
        this.dataConfirmacaoD.setEnabled(true);
        this.nomeTouroD.setEnabled(true);
        this.nomeVacaD.setEnabled(true);
        this.obsD.setEnabled(true);
        this.limparU.setEnabled(true);
        this.cancelarU.setEnabled(true);
        this.salvarU.setEnabled(true);
    }
    private void inclusaoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclusaoUActionPerformed
        this.habilitaCampos();
        aux_inclu = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_inclusaoUActionPerformed

    private void limparUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparUActionPerformed
        // TODO add your handling code here:
        this.limpaCampos();
    }//GEN-LAST:event_limparUActionPerformed

    private void cancelarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUActionPerformed
        this.limpaCampos();
        this.desabilitaCampos();
    }//GEN-LAST:event_cancelarUActionPerformed

    private void nomeVacaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeVacaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeVacaDActionPerformed

    private void codVacaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codVacaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codVacaDActionPerformed

    private void codTouroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTouroDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTouroDActionPerformed

    private void confirmadoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmadoSActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_confirmadoSActionPerformed
    public void retornaValorCio(int codCio,Date dataCio,int codvaca, String nomevaca,int codTouro, String nomeTouro) {
        this.codCioD.setText(Integer.toString(codCio));
        this.codVacaD.setText(Integer.toString(codvaca));
        this.nomeVacaD.setText(nomevaca);
        this.codTouroD.setText(Integer.toString(codTouro));
        this.nomeTouroD.setText(nomeTouro);
        this.dataCioD.setDate(dataCio);
    }
    private void pesquisaCioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaCioActionPerformed
        TelaPesquisaCios telaPB = new TelaPesquisaCios();
        telaPB.setTitle("RC MILK - PESQUISA DE CIOS");
        telaPB.enviavaloresCio(this);
        telaPB.IniciaTabela();
        telaPB.setVisible(true);

    }//GEN-LAST:event_pesquisaCioActionPerformed

    private void codCioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCioDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codCioDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacaoDeCio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacaoDeCio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacaoDeCio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacaoDeCio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfirmacaoDeCio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelExebicaodeCio;
    private javax.swing.JButton alterarU;
    private javax.swing.JButton cancelarU;
    private javax.swing.JTextField codCioD;
    private javax.swing.JLabel codCioL;
    private javax.swing.JTextField codTouroD;
    private javax.swing.JLabel codTouroL;
    private javax.swing.JTextField codVacaD;
    private javax.swing.JLabel codVacaL;
    private javax.swing.JCheckBox confirmadoS;
    private com.toedter.calendar.JDateChooser dataCioD;
    private javax.swing.JLabel dataCioL;
    private com.toedter.calendar.JDateChooser dataConfirmacaoD;
    private javax.swing.JLabel dataConfirmacaoL;
    private javax.swing.JButton inclusaoU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparU;
    private javax.swing.JTextField nomeTouroD;
    private javax.swing.JTextField nomeVacaD;
    private javax.swing.JTextPane obsD;
    private javax.swing.JLabel obsL;
    private javax.swing.JButton pesquisaCio;
    private javax.swing.JButton salvarU;
    // End of variables declaration//GEN-END:variables
}
