/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */

public class TelaCadastroUsuario extends javax.swing.JFrame {
    int aux_inclu = 0;
    int aux_altera = 0;
    int aux_excluir = 0;
    /**
     * Creates new form TelaCadastroBovino
     */
    public TelaCadastroUsuario() {
        initComponents();
        this.desabilitaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarU = new javax.swing.JButton();
        inclusaoU = new javax.swing.JButton();
        excluirU = new javax.swing.JButton();
        pesquisarU = new javax.swing.JButton();
        listarB = new javax.swing.JButton();
        nomeUsuarioL = new javax.swing.JLabel();
        usuarioL = new javax.swing.JLabel();
        salvarU = new javax.swing.JButton();
        nomeUsuarioD = new javax.swing.JTextField();
        ativoD = new javax.swing.JCheckBox();
        senhaL = new javax.swing.JLabel();
        usuarioD = new javax.swing.JTextField();
        emailD = new javax.swing.JTextField();
        emailL = new javax.swing.JLabel();
        telefoneL = new javax.swing.JLabel();
        telefoneD = new javax.swing.JFormattedTextField();
        senhaD = new javax.swing.JPasswordField();
        codD = new javax.swing.JTextField();
        limparU = new javax.swing.JButton();
        cancelarU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        alterarU.setText("Alterar");
        alterarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alterarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUActionPerformed(evt);
            }
        });

        inclusaoU.setText("Incluir");
        inclusaoU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inclusaoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclusaoUActionPerformed(evt);
            }
        });

        excluirU.setText("Excluir");
        excluirU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        excluirU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUActionPerformed(evt);
            }
        });

        pesquisarU.setText("Pesquisar");
        pesquisarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarUActionPerformed(evt);
            }
        });

        listarB.setText("Listar");
        listarB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBActionPerformed(evt);
            }
        });

        nomeUsuarioL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeUsuarioL.setText("Nome");

        usuarioL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        usuarioL.setText("Usuario");

        salvarU.setText("Salvar");
        salvarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salvarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarUActionPerformed(evt);
            }
        });

        nomeUsuarioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioDActionPerformed(evt);
            }
        });

        ativoD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ativoD.setText("Ativo");
        ativoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativoDActionPerformed(evt);
            }
        });

        senhaL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        senhaL.setText("Senha");

        usuarioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioDActionPerformed(evt);
            }
        });

        emailL.setText("E-mail");

        telefoneL.setText("Telefone");

        try {
            telefoneD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneDActionPerformed(evt);
            }
        });

        codD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codDActionPerformed(evt);
            }
        });

        limparU.setText("Limpar");
        limparU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limparU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparUActionPerformed(evt);
            }
        });

        cancelarU.setText("Cancelar");
        cancelarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inclusaoU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeUsuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisarU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(senhaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alterarU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(excluirU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(listarB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailD)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(senhaD)
                                .addGap(6, 6, 6)
                                .addComponent(telefoneL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salvarU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usuarioD, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ativoD, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeUsuarioD, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codD)
                                .addGap(3, 3, 3)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ativoD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefoneL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefoneD))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inclusaoU)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeUsuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nomeUsuarioD)
                                        .addComponent(codD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alterarU)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuarioL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usuarioD))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesquisarU)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(senhaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(senhaD))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirU)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailD))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listarB)
                            .addComponent(salvarU)
                            .addComponent(limparU)
                            .addComponent(cancelarU))))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUActionPerformed
        boolean aux;
        do{
            usuarioD.setText(JOptionPane.showInputDialog("Digite o Usuario:")); 
            Usuario user = new Usuario();
            user.setUser(usuarioD.getText());
            aux = user.pesquisar();
            if(aux){
                codD.setText(Integer.toString(user.getCodigo()));
                ativoD.setSelected(user.getAtivo());
                nomeUsuarioD.setText(user.getNome());
                usuarioD.setText(user.getUser());
                senhaD.setText(user.getSenha());
                telefoneD.setText(user.getTelefone());
                emailD.setText(user.getEmail());
                this.habilitaCampos();
                aux_altera = 1;
                
            }
        }while(!aux);
    }//GEN-LAST:event_alterarUActionPerformed

    private void listarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBActionPerformed
        TelaListagem telaLU = new TelaListagem();
        telaLU.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_listarBActionPerformed
    
    private void salvarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarUActionPerformed
        // TODO add your handling code here:
        if(aux_inclu == 1){
            Usuario user = new Usuario();
            user.setAtivo(ativoD.isSelected());
            user.setNome(nomeUsuarioD.getText());
            user.setUser(usuarioD.getText());
            user.setSenha(senhaD.getText());
            user.setTelefone(telefoneD.getText());
            user.setEmail(emailD.getText());
            if(nomeUsuarioD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Nome não pode ser vazio");
            }if(usuarioD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Usuario não pode ser vazio");
            }if(senhaD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Senha não pode ser vazio");
            }else{
                user.cadastrar();
                this.desabilitaCampos();
                aux_inclu = 0;
            }
        }if(aux_altera == 1){
            Usuario user = new Usuario();
            user.setCodigo(Integer.parseInt(codD.getText()));
            user.setAtivo(ativoD.isSelected());
            user.setNome(nomeUsuarioD.getText());
            user.setUser(usuarioD.getText());
            user.setSenha(senhaD.getText());
            user.setTelefone(telefoneD.getText());
            user.setEmail(emailD.getText());
            if(nomeUsuarioD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Nome não pode ser vazio");
            }if(usuarioD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Usuario não pode ser vazio");
            }if(senhaD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Senha não pode ser vazio");
            }else{
                user.alterar();
                this.desabilitaCampos();
                aux_altera = 0;
                this.limpaCampos();
            }
        }if(aux_excluir == 1){
            Usuario user = new Usuario();
            user.setCodigo(Integer.parseInt(codD.getText()));
            user.setAtivo(ativoD.isSelected());
            user.setNome(nomeUsuarioD.getText());
            user.setUser(usuarioD.getText());
            user.setSenha(senhaD.getText());
            user.setTelefone(telefoneD.getText());
            user.setEmail(emailD.getText());
            if(nomeUsuarioD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Nome não pode ser vazio");
            }if(usuarioD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Usuario não pode ser vazio");
            }if(senhaD.getText().equals("")){
               JOptionPane.showMessageDialog(null, "Campo Senha não pode ser vazio");
            }else{
                user.excluir();
                this.desabilitaCampos();
                aux_altera = 0;
                this.limpaCampos();
            }
        
        }
       
    }//GEN-LAST:event_salvarUActionPerformed
    public void limpaCampos(){
        ativoD.setHideActionText(false);
        nomeUsuarioD.setText("");
        usuarioD.setText("");
        senhaD.setText("");
        telefoneD.setText("");
        emailD.setText("");
    }
    private void ativoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativoDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ativoDActionPerformed

    private void nomeUsuarioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioDActionPerformed

    private void telefoneDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneDActionPerformed

    private void usuarioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioDActionPerformed

    private void inclusaoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclusaoUActionPerformed
        this.habilitaCampos();
        aux_inclu = 1;
        // TODO add your handling code here:
    }//GEN-LAST:event_inclusaoUActionPerformed

    private void pesquisarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarUActionPerformed
        usuarioD.setText(JOptionPane.showInputDialog("Digite o Usuario:"));
        Usuario user = new Usuario();
        user.setUser(usuarioD.getText());
        user.pesquisar();
        codD.setText(Integer.toString(user.getCodigo()));
        ativoD.setSelected(user.getAtivo());
        nomeUsuarioD.setText(user.getNome());
        usuarioD.setText(user.getUser());
        senhaD.setText(user.getSenha());
        telefoneD.setText(user.getTelefone());
        emailD.setText(user.getEmail());
        
    }//GEN-LAST:event_pesquisarUActionPerformed

    private void limparUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparUActionPerformed
        // TODO add your handling code here:
        this.limpaCampos();
    }//GEN-LAST:event_limparUActionPerformed
    public void desabilitaCampos(){
                nomeUsuarioD.setEnabled(false);
                ativoD.setEnabled(false);
                codD.setEnabled(false);
                emailD.setEnabled(false);
                salvarU.setEnabled(false);
                senhaD.setEnabled(false);
                telefoneD.setEnabled(false);
                usuarioD.setEnabled(false);
                limparU.setEnabled(false);
                cancelarU.setEnabled(false);
    }
    public void habilitaCampos(){
        nomeUsuarioD.setEnabled(true);
        ativoD.setEnabled(true);
        emailD.setEnabled(true);
        salvarU.setEnabled(true);
        senhaD.setEnabled(true);
        telefoneD.setEnabled(true);
        usuarioD.setEnabled(true);
        limparU.setEnabled(true);
        cancelarU.setEnabled(true);
    }
    private void cancelarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUActionPerformed
        // TODO add your handling code here:
        this.limpaCampos();
        aux_inclu = 0;    
        nomeUsuarioD.setEnabled(false);
        ativoD.setEnabled(false);
        codD.setEnabled(false);
        emailD.setEnabled(false);
        salvarU.setEnabled(false);
        senhaD.setEnabled(false);
        telefoneD.setEnabled(false);
        usuarioD.setEnabled(false);
        limparU.setEnabled(false);
        cancelarU.setEnabled(false);
    }//GEN-LAST:event_cancelarUActionPerformed

    private void codDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codDActionPerformed

    private void excluirUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUActionPerformed
        boolean aux;
        do{
            usuarioD.setText(JOptionPane.showInputDialog("Digite o Usuario:")); 
            Usuario user = new Usuario();
            user.setUser(usuarioD.getText());
            aux = user.pesquisar();
            if(aux){
                codD.setText(Integer.toString(user.getCodigo()));
                ativoD.setSelected(user.getAtivo());
                nomeUsuarioD.setText(user.getNome());
                usuarioD.setText(user.getUser());
                senhaD.setText(user.getSenha());
                telefoneD.setText(user.getTelefone());
                emailD.setText(user.getEmail());
                this.habilitaCampos();
                aux_excluir = 1;  
            }
        }while(!aux);        // TODO add your handling code here:
    }//GEN-LAST:event_excluirUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarU;
    private javax.swing.JCheckBox ativoD;
    private javax.swing.JButton cancelarU;
    private javax.swing.JTextField codD;
    private javax.swing.JTextField emailD;
    private javax.swing.JLabel emailL;
    private javax.swing.JButton excluirU;
    private javax.swing.JButton inclusaoU;
    private javax.swing.JButton limparU;
    private javax.swing.JButton listarB;
    private javax.swing.JTextField nomeUsuarioD;
    private javax.swing.JLabel nomeUsuarioL;
    private javax.swing.JButton pesquisarU;
    private javax.swing.JButton salvarU;
    private javax.swing.JPasswordField senhaD;
    private javax.swing.JLabel senhaL;
    private javax.swing.JFormattedTextField telefoneD;
    private javax.swing.JLabel telefoneL;
    private javax.swing.JTextField usuarioD;
    private javax.swing.JLabel usuarioL;
    // End of variables declaration//GEN-END:variables
}
