/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Conec;
import Controller.PostgresBackup;
import Model.Bovino;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rodri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaPrincipal() {
        initComponents();
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, e);
        }
        this.setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoTelaPrincipal = new javax.swing.JLabel();
        painelAT = new javax.swing.JPanel();
        AT_Bovino = new javax.swing.JButton();
        AT_USUARIO1 = new javax.swing.JButton();
        AT_fazenda = new javax.swing.JButton();
        AT_sair = new javax.swing.JButton();
        AT_backup = new javax.swing.JButton();
        AT_Cio = new javax.swing.JButton();
        AT_Confirmacao = new javax.swing.JButton();
        AT_Repetiu = new javax.swing.JButton();
        AT_Pre_parto = new javax.swing.JButton();
        AT_Perdeu = new javax.swing.JButton();
        AT_Parto = new javax.swing.JButton();
        painelInfo1 = new javax.swing.JPanel();
        fazendaLogada1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelInfo = new javax.swing.JPanel();
        usuarioLogadoInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelInfo4 = new javax.swing.JPanel();
        propLogado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        cadastroM = new javax.swing.JMenu();
        bovinoM = new javax.swing.JMenuItem();
        fazendaM = new javax.swing.JMenuItem();
        usuarioM = new javax.swing.JMenuItem();
        eventosM = new javax.swing.JMenu();
        reproducaoM = new javax.swing.JMenu();
        cadastroCioM = new javax.swing.JMenuItem();
        cioRepetidoM = new javax.swing.JMenuItem();
        confirmaCioM = new javax.swing.JMenuItem();
        prePartoM = new javax.swing.JMenuItem();
        perdaCriaM = new javax.swing.JMenuItem();
        partoM = new javax.swing.JMenuItem();
        relatorioM = new javax.swing.JMenu();
        relcadastro = new javax.swing.JMenu();
        usuarioRel = new javax.swing.JMenuItem();
        rel_cad_bov = new javax.swing.JMenuItem();
        rel_quanti_perdas = new javax.swing.JMenu();
        previsaoParto = new javax.swing.JMenuItem();
        Cio_por_Vaca = new javax.swing.JMenuItem();
        mtouros = new javax.swing.JMenuItem();
        CiosRepetidosTouros = new javax.swing.JMenuItem();
        relPreParto = new javax.swing.JMenuItem();
        relpreparto = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        rel_quant_cio_vaca = new javax.swing.JMenuItem();
        rel_desempenho_vacas = new javax.swing.JMenuItem();
        rel_desempenho_touro = new javax.swing.JMenuItem();
        relproducao = new javax.swing.JMenu();
        utilitariosM = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        trocarUsuarioM = new javax.swing.JMenuItem();
        BackupM = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_TelaPrincipal.png"))); // NOI18N

        painelAT.setBackground(new java.awt.Color(255, 255, 255));

        AT_Bovino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/at_bovino.png"))); // NOI18N
        AT_Bovino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_BovinoActionPerformed(evt);
            }
        });

        AT_USUARIO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/at_usuario.png"))); // NOI18N
        AT_USUARIO1.setBorder(null);
        AT_USUARIO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_USUARIO1ActionPerformed(evt);
            }
        });

        AT_fazenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/at_fazenda.png"))); // NOI18N
        AT_fazenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_fazendaActionPerformed(evt);
            }
        });

        AT_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/at_sair.png"))); // NOI18N
        AT_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_sairActionPerformed(evt);
            }
        });

        AT_backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/at_backup.png"))); // NOI18N
        AT_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_backupActionPerformed(evt);
            }
        });

        AT_Cio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icones/at_cio.png"))); // NOI18N
        AT_Cio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_CioActionPerformed(evt);
            }
        });

        AT_Confirmacao.setBackground(new java.awt.Color(51, 51, 51));
        AT_Confirmacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_ConfirmacaoActionPerformed(evt);
            }
        });

        AT_Repetiu.setBackground(new java.awt.Color(102, 102, 102));
        AT_Repetiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_RepetiuActionPerformed(evt);
            }
        });

        AT_Pre_parto.setBackground(new java.awt.Color(51, 51, 51));
        AT_Pre_parto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_Pre_partoActionPerformed(evt);
            }
        });

        AT_Perdeu.setBackground(new java.awt.Color(51, 51, 51));
        AT_Perdeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_PerdeuActionPerformed(evt);
            }
        });

        AT_Parto.setBackground(new java.awt.Color(51, 51, 51));
        AT_Parto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AT_PartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelATLayout = new javax.swing.GroupLayout(painelAT);
        painelAT.setLayout(painelATLayout);
        painelATLayout.setHorizontalGroup(
            painelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelATLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AT_USUARIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_fazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_Bovino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AT_Cio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_Repetiu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_Confirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AT_Pre_parto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_Perdeu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_Parto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AT_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AT_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelATLayout.setVerticalGroup(
            painelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelATLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelATLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AT_Parto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_Perdeu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_Pre_parto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_Repetiu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_Confirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_Cio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_Bovino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_fazenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AT_USUARIO1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelInfo1.setBackground(new java.awt.Color(255, 255, 255));
        painelInfo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fazendaLogada1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        fazendaLogada1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("Fazenda:");

        javax.swing.GroupLayout painelInfo1Layout = new javax.swing.GroupLayout(painelInfo1);
        painelInfo1.setLayout(painelInfo1Layout);
        painelInfo1Layout.setHorizontalGroup(
            painelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fazendaLogada1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        painelInfo1Layout.setVerticalGroup(
            painelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fazendaLogada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelInfo.setBackground(new java.awt.Color(255, 255, 255));
        painelInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usuarioLogadoInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        usuarioLogadoInfo.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout painelInfoLayout = new javax.swing.GroupLayout(painelInfo);
        painelInfo.setLayout(painelInfoLayout);
        painelInfoLayout.setHorizontalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioLogadoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        painelInfoLayout.setVerticalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(usuarioLogadoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelInfo4.setBackground(new java.awt.Color(255, 255, 255));
        painelInfo4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        propLogado.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        propLogado.setText("jLabel1");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setText("Proprietario:");

        javax.swing.GroupLayout painelInfo4Layout = new javax.swing.GroupLayout(painelInfo4);
        painelInfo4.setLayout(painelInfo4Layout);
        painelInfo4Layout.setHorizontalGroup(
            painelInfo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propLogado, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelInfo4Layout.setVerticalGroup(
            painelInfo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(propLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuBarra.setBackground(new java.awt.Color(102, 102, 102));

        cadastroM.setText("Cadastro");
        cadastroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMActionPerformed(evt);
            }
        });

        bovinoM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bovinoM.setText("Bovino");
        bovinoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bovinoMActionPerformed(evt);
            }
        });
        cadastroM.add(bovinoM);

        fazendaM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        fazendaM.setText("Fazenda");
        fazendaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazendaMActionPerformed(evt);
            }
        });
        cadastroM.add(fazendaM);

        usuarioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        usuarioM.setText("Usuário");
        usuarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMActionPerformed(evt);
            }
        });
        cadastroM.add(usuarioM);

        menuBarra.add(cadastroM);

        eventosM.setText("Eventos");

        reproducaoM.setText("Reprodução");

        cadastroCioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        cadastroCioM.setText("Cadastro de Cio");
        cadastroCioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCioMActionPerformed(evt);
            }
        });
        reproducaoM.add(cadastroCioM);

        cioRepetidoM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        cioRepetidoM.setText("Cio Repetido");
        cioRepetidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cioRepetidoMActionPerformed(evt);
            }
        });
        reproducaoM.add(cioRepetidoM);

        confirmaCioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        confirmaCioM.setText("Confirmaçao de Cio");
        confirmaCioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaCioMActionPerformed(evt);
            }
        });
        reproducaoM.add(confirmaCioM);

        prePartoM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        prePartoM.setText("Pre-Parto");
        prePartoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prePartoMActionPerformed(evt);
            }
        });
        reproducaoM.add(prePartoM);

        perdaCriaM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        perdaCriaM.setText("Perda de Cria");
        perdaCriaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdaCriaMActionPerformed(evt);
            }
        });
        reproducaoM.add(perdaCriaM);

        partoM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        partoM.setText("Parto");
        partoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partoMActionPerformed(evt);
            }
        });
        reproducaoM.add(partoM);

        eventosM.add(reproducaoM);

        menuBarra.add(eventosM);

        relatorioM.setText("Relatorios");

        relcadastro.setText("Cadastro");

        usuarioRel.setText("Relatorio Usuario");
        usuarioRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioRelActionPerformed(evt);
            }
        });
        relcadastro.add(usuarioRel);

        rel_cad_bov.setText("Relatorio Bovino");
        rel_cad_bov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_cad_bovActionPerformed(evt);
            }
        });
        relcadastro.add(rel_cad_bov);

        relatorioM.add(relcadastro);

        rel_quanti_perdas.setText("Reproducao");
        rel_quanti_perdas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_quanti_perdasActionPerformed(evt);
            }
        });

        previsaoParto.setText("Previsão de Parto");
        previsaoParto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previsaoPartoActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(previsaoParto);

        Cio_por_Vaca.setText("Cio por Vaca");
        Cio_por_Vaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cio_por_VacaActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(Cio_por_Vaca);

        mtouros.setText("Montas por Touros");
        mtouros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtourosActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(mtouros);

        CiosRepetidosTouros.setText("Cios Repetidos Touros");
        CiosRepetidosTouros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiosRepetidosTourosActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(CiosRepetidosTouros);

        relPreParto.setText("Planejamento Pre - Parto");
        relPreParto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relPrePartoActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(relPreParto);

        relpreparto.setText("Vaca em Pre - Parto");
        relpreparto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relprepartoActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(relpreparto);

        jMenuItem3.setText("Quantidade Perdas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(jMenuItem3);

        rel_quant_cio_vaca.setText("Quantidades de Cio Por vacas");
        rel_quant_cio_vaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_quant_cio_vacaActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(rel_quant_cio_vaca);

        rel_desempenho_vacas.setText("Desempenho Vacas");
        rel_desempenho_vacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_desempenho_vacasActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(rel_desempenho_vacas);

        rel_desempenho_touro.setText("Desempenho Touro");
        rel_desempenho_touro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rel_desempenho_touroActionPerformed(evt);
            }
        });
        rel_quanti_perdas.add(rel_desempenho_touro);

        relatorioM.add(rel_quanti_perdas);

        relproducao.setText("Produção");
        relatorioM.add(relproducao);

        menuBarra.add(relatorioM);

        utilitariosM.setText("Utilitário");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        utilitariosM.add(jMenuItem2);

        trocarUsuarioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        trocarUsuarioM.setText("Trocar Usuário");
        trocarUsuarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarUsuarioMActionPerformed(evt);
            }
        });
        utilitariosM.add(trocarUsuarioM);

        BackupM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        BackupM.setText("Backup");
        BackupM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackupMActionPerformed(evt);
            }
        });
        utilitariosM.add(BackupM);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem1.setText("Suporte");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        utilitariosM.add(jMenuItem1);

        menuBarra.add(utilitariosM);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(painelInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(painelInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(logoTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(799, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/LogoRCIcon.png")));
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void usuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMActionPerformed
        // TODO add your handling code here:
        TelaCadastroUsuario telaU = new TelaCadastroUsuario();
        telaU.setVisible(true);
        telaU.setTitle("RC MILK - CADASTRO USUARIOS");
    }//GEN-LAST:event_usuarioMActionPerformed

    private void trocarUsuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarUsuarioMActionPerformed
        Tela_login telaL = new Tela_login();
        this.dispose();
        telaL.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_trocarUsuarioMActionPerformed

    private void bovinoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bovinoMActionPerformed
        TelaCadastroBovino telaB = new TelaCadastroBovino();
        telaB.setTitle("RC MILK - CADASTRAR BOVINOS");
        telaB.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_bovinoMActionPerformed

    private void cadastroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroMActionPerformed

    private void fazendaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazendaMActionPerformed
        TelaCadastroFazenda telaF = new TelaCadastroFazenda();
        telaF.setTitle("RC MILK - CADASTRAR FAZENDA");
        telaF.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_fazendaMActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String sql = "select nome_usuario,telefone,email from tb_usuario where id_usuario = 1";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            Icon figura = new ImageIcon(getToolkit().createImage(getClass().getResource("/Imagens/suporte.png")));
            JOptionPane.showMessageDialog(null, "Entre em contato com:\nSuporte: " + rs.getString("nome_usuario")
                    + "\nTelefone: " + rs.getString("telefone") + "\nE-mail: "
                    + rs.getString("email"), "RC MILK - SUPORTE", JOptionPane.PLAIN_MESSAGE, figura);
        } catch (SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BackupMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupMActionPerformed

        try {
            PostgresBackup.realizaBackup();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BackupMActionPerformed

    private void AT_BovinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_BovinoActionPerformed
        TelaCadastroBovino telaB = new TelaCadastroBovino();
        telaB.setTitle("RC MILK - CADASTRAR BOVINOS");
        telaB.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_AT_BovinoActionPerformed

    private void AT_fazendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_fazendaActionPerformed
        TelaCadastroFazenda telaF = new TelaCadastroFazenda();
        telaF.setTitle("RC MILK - CADASTRAR FAZENDA");
        telaF.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AT_fazendaActionPerformed

    private void AT_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_sairActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_AT_sairActionPerformed

    private void AT_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_backupActionPerformed
        try {
            PostgresBackup.realizaBackup();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_AT_backupActionPerformed

    private void AT_USUARIO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_USUARIO1ActionPerformed
        TelaCadastroUsuario telaU = new TelaCadastroUsuario();
        telaU.setVisible(true);
        telaU.setTitle("RC MILK - CADASTRO USUARIOS");        // TODO add your handling code here:
    }//GEN-LAST:event_AT_USUARIO1ActionPerformed

    private void AT_CioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_CioActionPerformed
        TelaCadastroCio telaC = new TelaCadastroCio();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - CIOS");        // TODO add your handling code here:
    }//GEN-LAST:event_AT_CioActionPerformed

    private void cadastroCioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCioMActionPerformed
        TelaCadastroCio telaC = new TelaCadastroCio();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - CIOS");
    }//GEN-LAST:event_cadastroCioMActionPerformed

    private void cioRepetidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cioRepetidoMActionPerformed
        TelaRepetiuCio telaC = new TelaRepetiuCio();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - REPETIU DE CIO");
    }//GEN-LAST:event_cioRepetidoMActionPerformed

    private void confirmaCioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaCioMActionPerformed
        TelaConfirmacaoDeCio telaC = new TelaConfirmacaoDeCio();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - CONFIRMACAO DE CIOS");
    }//GEN-LAST:event_confirmaCioMActionPerformed

    private void prePartoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prePartoMActionPerformed
        TelaPreParto telaC = new TelaPreParto();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - Pre-Parto");
    }//GEN-LAST:event_prePartoMActionPerformed

    private void perdaCriaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdaCriaMActionPerformed
        TelaPerdaCria telaC = new TelaPerdaCria();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - Perda de Cria");
    }//GEN-LAST:event_perdaCriaMActionPerformed

    private void partoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partoMActionPerformed
        TelaParto telaC = new TelaParto();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - Parto");
    }//GEN-LAST:event_partoMActionPerformed

    private void AT_ConfirmacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_ConfirmacaoActionPerformed
        TelaConfirmacaoDeCio telaC = new TelaConfirmacaoDeCio();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - CONFIRMACAO DE CIOS");
    }//GEN-LAST:event_AT_ConfirmacaoActionPerformed

    private void AT_RepetiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_RepetiuActionPerformed
        TelaRepetiuCio telaC = new TelaRepetiuCio();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - REPETIU DE CIO");
    }//GEN-LAST:event_AT_RepetiuActionPerformed

    private void AT_Pre_partoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_Pre_partoActionPerformed
        TelaPreParto telaC = new TelaPreParto();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - Pre-Parto");
    }//GEN-LAST:event_AT_Pre_partoActionPerformed

    private void AT_PerdeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_PerdeuActionPerformed
        TelaPerdaCria telaC = new TelaPerdaCria();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - Perda de Cria");
    }//GEN-LAST:event_AT_PerdeuActionPerformed

    private void AT_PartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AT_PartoActionPerformed
        TelaParto telaC = new TelaParto();
        telaC.setVisible(true);
        telaC.setTitle("RC MILK - Parto");
    }//GEN-LAST:event_AT_PartoActionPerformed

    private void rel_cad_bovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_cad_bovActionPerformed
        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null, rs1 = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("SELECT tb_bovino.cod AS tb_bovino_cod,tb_bovino.ativo AS tb_bovino_ativo,tb_bovino.nome AS tb_bovino_nome,tb_bovino.brinco AS tb_bovino_brinco,tb_bovino.idade AS tb_bovino_idade,tb_bovino.sexo AS tb_bovino_sexo,tb_bovino.raca AS tb_bovino_raca,tb_bovino.cor AS tb_bovino_cor,tb_bovino.quantcria AS tb_bovino_quantcria,tb_bovino.observacao AS tb_bovino_observacao,tb_bovino.nome_pai AS tb_bovino_nome_pai,tb_bovino.nome_mae AS tb_bovino_nome_mae,tb_bovino.data_nasc AS tb_bovino_data_nasc,tb_fazenda.id_fazenda AS tb_fazenda_id_fazenda,tb_fazenda.ativo AS tb_fazenda_ativo,tb_fazenda.nome_fazenda AS tb_fazenda_nome_fazenda,tb_fazenda.nome_prop AS tb_fazenda_nome_prop,tb_fazenda.cfp_prop AS tb_fazenda_cfp_prop,tb_fazenda.insc_estadual AS tb_fazenda_insc_estadual,tb_fazenda.telefone AS tb_fazenda_telefone,tb_fazenda.celular AS tb_fazenda_celular,tb_fazenda.email AS tb_fazenda_email FROM public.tb_bovino tb_bovino,public.tb_fazenda tb_fazenda;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        }
        try {
            
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_cadastro_bovinos.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_rel_cad_bovActionPerformed

    private void usuarioRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioRelActionPerformed
        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select id_usuario,ativo,nome_usuario,usuario,telefone,email from tb_usuario;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_cadastro_usuario.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_usuarioRelActionPerformed

    private void previsaoPartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previsaoPartoActionPerformed
        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("SELECT codcio, datacio, codvaca, nomevaca, codtouro, nometouro, confirmado, dataconfirmacao, repetiucio, obs, perdeu, dataparto, parto, dataperda, finalizado, pre_parto, data_preparto, previsao_parto FROM tb_cio WHERE tb_cio.finalizado = false;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_reproducao_previsao_parto.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_previsaoPartoActionPerformed

    private void Cio_por_VacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cio_por_VacaActionPerformed
        TelaRelatorioDeCioPorVacas telaRC = new TelaRelatorioDeCioPorVacas();
        telaRC.setVisible(true);
        telaRC.IniciaTabela();
        telaRC.setTitle("RC MILK - Relatorio de Cio");
    }//GEN-LAST:event_Cio_por_VacaActionPerformed

    private void rel_quanti_perdasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_quanti_perdasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rel_quanti_perdasActionPerformed

    private void mtourosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtourosActionPerformed
        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select nometouro, count (nometouro) from tb_cio group by nometouro;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_monta_touro.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mtourosActionPerformed

    private void CiosRepetidosTourosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiosRepetidosTourosActionPerformed
        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select nometouro, count (nometouro) from tb_cio where repetiucio = true group by nometouro");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_monta_touro_repetidos.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CiosRepetidosTourosActionPerformed

    private void relPrePartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relPrePartoActionPerformed
               Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select nomevaca , previsao_parto - 60 as DATA_PARA_PRE_PARTO , previsao_parto from tb_cio where confirmado = true and finalizado <> true;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_planejamento_pre_parto.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_relPrePartoActionPerformed

    private void relprepartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relprepartoActionPerformed

        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select codcio, nomevaca, previsao_parto, data_preparto  from tb_cio where pre_parto = true and finalizado <> true;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_pre_parto.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_relprepartoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select nomevaca, count(perdeu = true) from tb_cio where perdeu =  true group by nomevaca;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_quant_perdas.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void rel_quant_cio_vacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_quant_cio_vacaActionPerformed
                Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = ("select nomevaca, count(codcio) from tb_cio  group by nomevaca;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_quant_cio_vaca.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rel_quant_cio_vacaActionPerformed

    private void rel_desempenho_vacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_desempenho_vacasActionPerformed
        Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = (  "SELECT  c.codvaca, bov.nome, bov.brinco, bov.idade,bov.raca,bov.cor, bov.data_nasc,\n" +
                        "		count(codcio) as Quant_Cios,\n" +
                        "		SUM(CASE c.repetiucio WHEN TRUE THEN 1 ELSE 0 END) as Quant_Cios_rep,\n" +
                        "		SUM(CASE c.parto WHEN TRUE THEN 1 ELSE 0 END) as Quant_Cios_partos,\n" +
                        "		SUM(CASE c.perdeu WHEN TRUE THEN 1 ELSE 0 END) as Quant_Cios_Perdidos,\n" +
                        "		(COUNT(c.codcio)  - (SUM(CASE c.repetiucio WHEN TRUE THEN 1 ELSE 0 END)+\n" +
                        "						  SUM(CASE c.parto WHEN TRUE THEN 1 ELSE 0 END)+\n" +
                        "						  SUM(CASE c.perdeu WHEN TRUE THEN 1 ELSE 0 END))) as Quant_cios_Confirmados_Sem_Finalizar\n" +
                        "FROM tb_cio as c inner join tb_bovino as bov on c.codvaca = bov.cod\n" +
                        "GROUP BY c.codvaca,bov.cod\n" +
                        "ORDER BY c.codvaca;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_desempenho_vacas.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rel_desempenho_vacasActionPerformed

    private void rel_desempenho_touroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rel_desempenho_touroActionPerformed
                Connection con =null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Bovino.class.getName()).log(Level.SEVERE, null, e);
        }
        String sql = (  "SELECT  c.codtouro, bov.nome, bov.brinco, bov.sexo,bov.raca,bov.cor, bov.data_nasc,\n" +
                        "		count(codcio) as Quant_Cios,\n" +
                        "		SUM(CASE c.repetiucio WHEN TRUE THEN 1 ELSE 0 END) as Quant_Cios_rep,\n" +
                        "		SUM(CASE c.parto WHEN TRUE THEN 1 ELSE 0 END) as Quant_Cios_partos,\n" +
                        "		SUM(CASE c.perdeu WHEN TRUE THEN 1 ELSE 0 END) as Quant_Cios_Perdidos,\n" +
                        "		(COUNT(c.codcio)  - (SUM(CASE c.repetiucio WHEN TRUE THEN 1 ELSE 0 END)+\n" +
                        "						  SUM(CASE c.parto WHEN TRUE THEN 1 ELSE 0 END)+\n" +
                        "						  SUM(CASE c.perdeu WHEN TRUE THEN 1 ELSE 0 END))) as Quant_cios_Confirmados_Sem_Finalizar\n" +
                        "FROM tb_cio as c inner join tb_bovino as bov on c.codtouro = bov.cod\n" +
                        "GROUP BY c.codtouro,bov.cod\n" +
                        "ORDER BY c.codtouro;");
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);
            Map map = null;
            String url = "src\\Relatorios\\rel_desempenho_touro.jasper";
            System.out.println(url);
            JasperPrint jasperPrint  = JasperFillManager.fillReport(url,map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false );	  
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rel_desempenho_touroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AT_Bovino;
    private javax.swing.JButton AT_Cio;
    private javax.swing.JButton AT_Confirmacao;
    private javax.swing.JButton AT_Parto;
    private javax.swing.JButton AT_Perdeu;
    private javax.swing.JButton AT_Pre_parto;
    private javax.swing.JButton AT_Repetiu;
    private javax.swing.JButton AT_USUARIO1;
    private javax.swing.JButton AT_backup;
    private javax.swing.JButton AT_fazenda;
    private javax.swing.JButton AT_sair;
    private javax.swing.JMenuItem BackupM;
    private javax.swing.JMenuItem Cio_por_Vaca;
    private javax.swing.JMenuItem CiosRepetidosTouros;
    private javax.swing.JMenuItem bovinoM;
    private javax.swing.JMenuItem cadastroCioM;
    private javax.swing.JMenu cadastroM;
    private javax.swing.JMenuItem cioRepetidoM;
    private javax.swing.JMenuItem confirmaCioM;
    private javax.swing.JMenu eventosM;
    public javax.swing.JLabel fazendaLogada1;
    private javax.swing.JMenuItem fazendaM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel logoTelaPrincipal;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem mtouros;
    private javax.swing.JPanel painelAT;
    private javax.swing.JPanel painelInfo;
    private javax.swing.JPanel painelInfo1;
    private javax.swing.JPanel painelInfo4;
    private javax.swing.JMenuItem partoM;
    private javax.swing.JMenuItem perdaCriaM;
    private javax.swing.JMenuItem prePartoM;
    private javax.swing.JMenuItem previsaoParto;
    public javax.swing.JLabel propLogado;
    private javax.swing.JMenuItem relPreParto;
    private javax.swing.JMenuItem rel_cad_bov;
    private javax.swing.JMenuItem rel_desempenho_touro;
    private javax.swing.JMenuItem rel_desempenho_vacas;
    private javax.swing.JMenuItem rel_quant_cio_vaca;
    private javax.swing.JMenu rel_quanti_perdas;
    private javax.swing.JMenu relatorioM;
    private javax.swing.JMenu relcadastro;
    private javax.swing.JMenuItem relpreparto;
    private javax.swing.JMenu relproducao;
    private javax.swing.JMenu reproducaoM;
    private javax.swing.JMenuItem trocarUsuarioM;
    public javax.swing.JLabel usuarioLogadoInfo;
    private javax.swing.JMenuItem usuarioM;
    private javax.swing.JMenuItem usuarioRel;
    private javax.swing.JMenu utilitariosM;
    // End of variables declaration//GEN-END:variables
}
