/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Conec;
import Controller.PostgresBackup;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    Connection con =null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaPrincipal() {
        initComponents();
        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException e) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoTelaPrincipal = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        cadastroM = new javax.swing.JMenu();
        bovinoM = new javax.swing.JMenuItem();
        fazendaM = new javax.swing.JMenuItem();
        usuarioM = new javax.swing.JMenuItem();
        eventosM = new javax.swing.JMenu();
        cioM = new javax.swing.JMenuItem();
        relatorioM = new javax.swing.JMenu();
        utilitariosM = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        trocarUsuarioM = new javax.swing.JMenuItem();
        BackupM = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_TelaPrincipal.png"))); // NOI18N

        menuBarra.setBackground(new java.awt.Color(102, 102, 102));

        cadastroM.setText("Cadastro");
        cadastroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMActionPerformed(evt);
            }
        });

        bovinoM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bovinoM.setText("Bovino");
        bovinoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bovinoMActionPerformed(evt);
            }
        });
        cadastroM.add(bovinoM);

        fazendaM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        fazendaM.setText("Fazenda");
        fazendaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazendaMActionPerformed(evt);
            }
        });
        cadastroM.add(fazendaM);

        usuarioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        usuarioM.setText("Usuário");
        usuarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMActionPerformed(evt);
            }
        });
        cadastroM.add(usuarioM);

        menuBarra.add(cadastroM);

        eventosM.setText("Eventos");

        cioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        cioM.setText("Cio");
        eventosM.add(cioM);

        menuBarra.add(eventosM);

        relatorioM.setText("Relatorios");
        menuBarra.add(relatorioM);

        utilitariosM.setText("Utiliarios");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        utilitariosM.add(jMenuItem2);

        trocarUsuarioM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        trocarUsuarioM.setText("Trocar Usuário");
        trocarUsuarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarUsuarioMActionPerformed(evt);
            }
        });
        utilitariosM.add(trocarUsuarioM);

        BackupM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        BackupM.setText("Backup");
        BackupM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackupMActionPerformed(evt);
            }
        });
        utilitariosM.add(BackupM);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem1.setText("Suporte");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        utilitariosM.add(jMenuItem1);

        menuBarra.add(utilitariosM);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(553, Short.MAX_VALUE)
                .addComponent(logoTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(logoTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(799, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/LogoRCIcon.png")));  
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void usuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMActionPerformed
        // TODO add your handling code here:
         TelaCadastroUsuario telaU = new TelaCadastroUsuario();
         telaU.setVisible(true);
         telaU.setTitle("RC MILK - CADASTRO USUARIOS");
    }//GEN-LAST:event_usuarioMActionPerformed

    private void trocarUsuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarUsuarioMActionPerformed
         Tela_login telaL = new Tela_login();
         this.dispose();
         telaL.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_trocarUsuarioMActionPerformed

    private void bovinoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bovinoMActionPerformed
        TelaCadastroBovino telaB = new TelaCadastroBovino();
        telaB.setTitle("RC MILK - CADASTRAR BOVINOS");
        telaB.setVisible(true);    
        // TODO add your handling code here:
    }//GEN-LAST:event_bovinoMActionPerformed

    private void cadastroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroMActionPerformed

    private void fazendaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazendaMActionPerformed
        TelaCadastroFazenda telaF = new TelaCadastroFazenda();
        telaF.setTitle("RC MILK - CADASTRAR FAZENDA");
        telaF.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_fazendaMActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String sql = "select nome_usuario,telefone,email from tb_usuario where id_usuario = 1";
        try{
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            Icon figura = new ImageIcon (getToolkit().createImage(getClass().getResource("/Imagens/suporte.png"))); 
            JOptionPane.showMessageDialog(null, "Entre em contato com:\nSuporte: "+rs.getString("nome_usuario")+
                                          "\nTelefone: "+rs.getString("telefone")+"\nE-mail: "
                                          +rs.getString("email"), "RC MILK - SUPORTE", JOptionPane.PLAIN_MESSAGE, figura); 
        }catch(SQLException E){
            JOptionPane.showMessageDialog(null, E);
        } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BackupMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupMActionPerformed

            try {
            PostgresBackup.realizaBackup();
            } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
      
    }//GEN-LAST:event_BackupMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BackupM;
    private javax.swing.JMenuItem bovinoM;
    private javax.swing.JMenu cadastroM;
    private javax.swing.JMenuItem cioM;
    private javax.swing.JMenu eventosM;
    private javax.swing.JMenuItem fazendaM;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel logoTelaPrincipal;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu relatorioM;
    private javax.swing.JMenuItem trocarUsuarioM;
    private javax.swing.JMenuItem usuarioM;
    private javax.swing.JMenu utilitariosM;
    // End of variables declaration//GEN-END:variables
}
