/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Bovino;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class TelaCadastroBovino extends javax.swing.JFrame {

    int aux_inclu = 0;
    int aux_altera = 0;
    int aux_excluir = 0;

    /**
     * Creates new form TelaCadastroBovino
     */
    public TelaCadastroBovino() {
        initComponents();
        this.desabilitaCampos();
        this.limpaCampos();
        this.setIcon();

    }

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/LogoRCIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarB = new javax.swing.JButton();
        inclusaoB = new javax.swing.JButton();
        excluirB = new javax.swing.JButton();
        pesquisarB = new javax.swing.JButton();
        listarB = new javax.swing.JButton();
        nomeL = new javax.swing.JLabel();
        nomePaiD = new javax.swing.JTextField();
        BrincoL = new javax.swing.JLabel();
        BrincoD = new javax.swing.JTextField();
        ativoD = new javax.swing.JCheckBox();
        dataNascL = new javax.swing.JLabel();
        nomePaiL = new javax.swing.JLabel();
        nomeD = new javax.swing.JTextField();
        nomeMaeL = new javax.swing.JLabel();
        observacaoL = new javax.swing.JLabel();
        nomeMaeD = new javax.swing.JTextField();
        codBovinoL = new javax.swing.JLabel();
        codBovinoD = new javax.swing.JTextField();
        sexoD = new javax.swing.JComboBox<>();
        sexoL = new javax.swing.JLabel();
        racaL = new javax.swing.JLabel();
        racaD = new javax.swing.JTextField();
        corL = new javax.swing.JLabel();
        corD = new javax.swing.JFormattedTextField();
        observacaoD = new javax.swing.JTextArea();
        quantCriasL = new javax.swing.JLabel();
        quantCriasD = new javax.swing.JFormattedTextField();
        cancelarU = new javax.swing.JButton();
        limparU = new javax.swing.JButton();
        salvarU = new javax.swing.JButton();
        dataNascD = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        alterarB.setText("Alterar");
        alterarB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alterarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBActionPerformed(evt);
            }
        });

        inclusaoB.setText("Incluir");
        inclusaoB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inclusaoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclusaoBActionPerformed(evt);
            }
        });

        excluirB.setText("Excluir");
        excluirB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        excluirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBActionPerformed(evt);
            }
        });

        pesquisarB.setText("Pesquisar");
        pesquisarB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarBActionPerformed(evt);
            }
        });

        listarB.setText("Listar");
        listarB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBActionPerformed(evt);
            }
        });

        nomeL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomeL.setText("Nome:*");

        BrincoL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BrincoL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BrincoL.setText("Brinco:");
        BrincoL.setPreferredSize(null);

        BrincoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrincoDActionPerformed(evt);
            }
        });

        ativoD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ativoD.setText("Ativo");
        ativoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativoDActionPerformed(evt);
            }
        });

        dataNascL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dataNascL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dataNascL.setText("Data Nasc.:");

        nomePaiL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomePaiL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomePaiL.setText("Nome Pai:");

        nomeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDActionPerformed(evt);
            }
        });

        nomeMaeL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nomeMaeL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomeMaeL.setText("Nome Mãe:");

        observacaoL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        observacaoL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        observacaoL.setText("Obs.:");

        codBovinoL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        codBovinoL.setText("Cod.:");

        codBovinoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codBovinoDActionPerformed(evt);
            }
        });

        sexoD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Macho", "Fêmea" }));
        sexoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoDActionPerformed(evt);
            }
        });

        sexoL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sexoL.setText("Sexo");

        racaL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        racaL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        racaL.setText("Raça:");
        racaL.setPreferredSize(null);

        racaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racaDActionPerformed(evt);
            }
        });

        corL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        corL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        corL.setText("Cor:*");

        corD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corDActionPerformed(evt);
            }
        });

        observacaoD.setColumns(20);
        observacaoD.setLineWrap(true);
        observacaoD.setRows(5);

        quantCriasL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        quantCriasL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quantCriasL.setText("Quant. Crias:");

        quantCriasD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantCriasDActionPerformed(evt);
            }
        });

        cancelarU.setText("Cancelar");
        cancelarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarUActionPerformed(evt);
            }
        });

        limparU.setText("Limpar");
        limparU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limparU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparUActionPerformed(evt);
            }
        });

        salvarU.setText("Salvar");
        salvarU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salvarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(observacaoL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(observacaoD, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomePaiL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomePaiD, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeMaeL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeMaeD))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codBovinoL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrincoL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(racaL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(racaD, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(BrincoD, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(codBovinoD, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexoL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(corL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(corD, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(sexoD, 0, 100, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dataNascL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(quantCriasL, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(quantCriasD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(ativoD))
                                            .addComponent(dataNascD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(nomeD))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(limparU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(salvarU, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(listarB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alterarB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inclusaoB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisarB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codBovinoL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codBovinoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BrincoL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrincoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantCriasL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantCriasD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(racaL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(racaD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataNascL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataNascD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeMaeD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeMaeL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePaiD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomePaiL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observacaoL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(observacaoD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limparU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarU, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(inclusaoB)
                        .addGap(18, 18, 18)
                        .addComponent(alterarB)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisarB)
                        .addGap(18, 18, 18)
                        .addComponent(listarB)
                        .addGap(18, 18, 18)
                        .addComponent(excluirB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBActionPerformed
        this.limpaCampos();
        boolean aux;
        do {
            String imput;
            imput = (JOptionPane.showInputDialog(null, "Digite o Nome do Bovino:"));
            nomeD.setText(imput);
            if (imput == null) {
                System.out.println("Cancel is pressed");
                break;
            }
            Bovino bov = new Bovino();
            bov.setNome(nomeD.getText());
            aux = bov.pesquisar();
            if (aux) {
                codBovinoD.setText(Integer.toString(bov.getCod()));
                ativoD.setSelected(bov.isAtivo());
                nomeD.setText(bov.getNome());
                BrincoD.setText(Integer.toString(bov.getBrinco()));
                dataNascD.setDate(bov.getData_nasc());
                sexoD.setSelectedItem(bov.getSexo());
                racaD.setText(bov.getRaca());
                corD.setText(bov.getCor());
                quantCriasD.setText(Integer.toString(bov.getQuantCria()));
                observacaoD.setText(bov.getObservacao());
                nomePaiD.setText(bov.getNome_pai());
                nomeMaeD.setText(bov.getNome_mae());
                this.habilitaCampos();
                aux_altera = 1;
            }

        } while (!aux);          // TODO add your handling code here:
    }//GEN-LAST:event_alterarBActionPerformed

    private void ativoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativoDActionPerformed

    private void BrincoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrincoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrincoDActionPerformed

    private void codBovinoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codBovinoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codBovinoDActionPerformed

    private void sexoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoDActionPerformed

    private void racaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_racaDActionPerformed

    private void corDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corDActionPerformed

    private void quantCriasDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantCriasDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantCriasDActionPerformed

    private void nomeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDActionPerformed

    private void inclusaoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclusaoBActionPerformed
        // TODO add your handling code here:
        this.habilitaCampos();
        codBovinoD.setEnabled(false);
        aux_inclu = 1;
    }//GEN-LAST:event_inclusaoBActionPerformed
    public void cadastroBezerro(String nomeMae, String NomePai, Date dtNasc, String ObsParto) {
        this.habilitaCampos();
        aux_inclu = 1;
        this.dataNascD.setDate(dtNasc);
        this.observacaoD.setText(ObsParto);
        this.nomePaiD.setText(NomePai);
        this.nomeMaeD.setText(nomeMae);

    }
    private void pesquisarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarBActionPerformed
        this.limpaCampos();
        nomeD.setText(JOptionPane.showInputDialog("Digite o Nome do Bovino:"));
        Bovino bov = new Bovino();
        bov.setNome(nomeD.getText());
        bov.pesquisar();
        codBovinoD.setText(Integer.toString(bov.getCod()));
        ativoD.setSelected(bov.isAtivo());
        nomeD.setText(bov.getNome());
        BrincoD.setText(Integer.toString(bov.getBrinco()));
        dataNascD.setDate(bov.getData_nasc());
        dataNascD.setDate(bov.getData_nasc());
        sexoD.setSelectedItem(bov.getSexo());
        racaD.setText(bov.getRaca());
        corD.setText(bov.getCor());
        quantCriasD.setText(Integer.toString(bov.getQuantCria()));
        observacaoD.setText(bov.getObservacao());
        nomePaiD.setText(bov.getNome_pai());
        nomeMaeD.setText(bov.getNome_mae());

    }//GEN-LAST:event_pesquisarBActionPerformed

    private void cancelarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarUActionPerformed
        this.limpaCampos();
        aux_inclu = 0;
        aux_altera = 0;
        aux_excluir = 0;
        this.desabilitaCampos();
    }//GEN-LAST:event_cancelarUActionPerformed

    private void limparUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparUActionPerformed
        // TODO add your handling code here:
        this.limpaCampos();
    }//GEN-LAST:event_limparUActionPerformed

    private void salvarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarUActionPerformed
        // TODO add your handling code here:
        if (aux_inclu == 1) {
            Bovino bov = new Bovino();
            bov.setAtivo(ativoD.isSelected());
            bov.setNome(nomeD.getText());
            bov.setBrinco(Integer.parseInt(BrincoD.getText()));
            String vazia = ("");
            bov.setData_nasc(dataNascD.getDate());
            bov.setSexo((String) this.sexoD.getSelectedItem());
            bov.setRaca(racaD.getText());
            bov.setCor(corD.getText());
            if (quantCriasD.getText().equals(vazia)) {
                bov.setQuantCria(0);
            } else {
                bov.setQuantCria(Integer.parseInt(quantCriasD.getText()));
            }
            bov.setObservacao(observacaoD.getText());
            bov.setNome_pai(nomePaiD.getText());
            bov.setNome_mae(nomeMaeD.getText());
            if (nomeD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Nome Bovino não pode ser vazio");
            }
            if (corD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Cor Bovino não pode ser vazio");
            }
            if (corD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Cor Bovino não pode ser vazio");
            } else {
                bov.cadastrar();
                this.desabilitaCampos();
                aux_inclu = 0;
                this.limpaCampos();
            }
        }
        if (aux_altera == 1) {
            Bovino bov = new Bovino();
            bov.setCod(Integer.parseInt(codBovinoD.getText()));
            bov.setAtivo(ativoD.isSelected());
            bov.setNome(nomeD.getText());
            bov.setBrinco(Integer.parseInt(BrincoD.getText()));
            bov.setData_nasc(dataNascD.getDate());
            bov.setSexo((String) this.sexoD.getSelectedItem());
            bov.setRaca(racaD.getText());
            bov.setCor(corD.getText());
            bov.setQuantCria(Integer.parseInt(quantCriasD.getText()));
            bov.setObservacao(observacaoD.getText());
            bov.setNome_pai(nomePaiD.getText());
            bov.setNome_mae(nomeMaeD.getText());
            if (nomeD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Nome Bovino não pode ser vazio");
            }
            if (corD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Cor Bovino não pode ser vazio");
            }
            if (corD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Cor Bovino não pode ser vazio");
            } else {
                bov.alterar();
                this.desabilitaCampos();
                aux_altera = 0;
                this.limpaCampos();
            }
        }
        if (aux_excluir == 1) {
            Bovino bov = new Bovino();
            bov.setCod(Integer.parseInt(codBovinoD.getText()));
            bov.setAtivo(ativoD.isSelected());
            bov.setNome(nomeD.getText());
            bov.setBrinco(Integer.parseInt(BrincoD.getText()));
            bov.setData_nasc(dataNascD.getDate());
            bov.setSexo((String) this.sexoD.getSelectedItem());
            bov.setRaca(racaD.getText());
            bov.setCor(corD.getText());
            bov.setQuantCria(Integer.parseInt(quantCriasD.getText()));
            bov.setObservacao(observacaoD.getText());
            bov.setNome_pai(nomePaiD.getText());
            bov.setNome_mae(nomeMaeD.getText());
            if (nomeD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Nome Bovino não pode ser vazio");
            }
            if (corD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Cor Bovino não pode ser vazio");
            }
            if (corD.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo Cor Bovino não pode ser vazio");
            } else {
                bov.excluir();
                this.desabilitaCampos();
                aux_excluir = 0;
                this.limpaCampos();
            }
        }
    }//GEN-LAST:event_salvarUActionPerformed

    private void excluirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBActionPerformed
        this.limpaCampos();
        boolean aux;
        do {
            String imput;
            imput = (JOptionPane.showInputDialog(null, "Digite o Nome do Bovino:"));
            nomeD.setText(imput);
            if (imput == null) {
                System.out.println("Cancel is pressed");
                break;
            }
            Bovino bov = new Bovino();
            bov.setNome(nomeD.getText());
            aux = bov.pesquisar();
            if (aux) {
                codBovinoD.setText(Integer.toString(bov.getCod()));
                ativoD.setSelected(bov.isAtivo());
                nomeD.setText(bov.getNome());
                BrincoD.setText(Integer.toString(bov.getBrinco()));
                dataNascD.setDate(bov.getData_nasc());
                sexoD.setSelectedItem(bov.getSexo());
                racaD.setText(bov.getRaca());
                corD.setText(bov.getCor());
                quantCriasD.setText(Integer.toString(bov.getQuantCria()));
                observacaoD.setText(bov.getObservacao());
                nomePaiD.setText(bov.getNome_pai());
                nomeMaeD.setText(bov.getNome_mae());
                aux_excluir = 1;
            }

        } while (!aux);        // TODO add your handling code here:
    }//GEN-LAST:event_excluirBActionPerformed

    private void listarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBActionPerformed
        TelaListagemBovinos telaLB = new TelaListagemBovinos();
        telaLB.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_listarBActionPerformed

    public void habilitaCampos() {

        ativoD.setEnabled(true);
        nomeD.setEnabled(true);
        BrincoD.setEnabled(true);
        dataNascD.setEnabled(true);
        sexoD.setEnabled(true);
        racaD.setEnabled(true);
        corD.setEnabled(true);
        quantCriasD.setEnabled(true);
        observacaoD.setEnabled(true);
        nomePaiD.setEnabled(true);
        nomeMaeD.setEnabled(true);
        limparU.setEnabled(true);
        cancelarU.setEnabled(true);
        salvarU.setEnabled(true);

    }

    public void desabilitaCampos() {

        codBovinoD.setEnabled(false);
        ativoD.setEnabled(false);
        nomeD.setEnabled(false);
        BrincoD.setEnabled(false);
        dataNascD.setEnabled(false);
        sexoD.setEnabled(false);
        racaD.setEnabled(false);
        corD.setEnabled(false);
        quantCriasD.setEnabled(false);
        observacaoD.setEnabled(false);
        nomePaiD.setEnabled(false);
        nomeMaeD.setEnabled(false);
        limparU.setEnabled(false);
        cancelarU.setEnabled(false);
        salvarU.setEnabled(false);

    }

    public void limpaCampos() {

        codBovinoD.setText("");
        ativoD.setSelected(false);
        nomeD.setText("");
        BrincoD.setText("");
        sexoD.setSelectedIndex(2);
        racaD.setText("");
        corD.setText("");
        quantCriasD.setText("");
        observacaoD.setText("");
        nomePaiD.setText("");
        nomeMaeD.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBovino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroBovino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BrincoD;
    private javax.swing.JLabel BrincoL;
    private javax.swing.JButton alterarB;
    private javax.swing.JCheckBox ativoD;
    private javax.swing.JButton cancelarU;
    private javax.swing.JTextField codBovinoD;
    private javax.swing.JLabel codBovinoL;
    private javax.swing.JFormattedTextField corD;
    private javax.swing.JLabel corL;
    private com.toedter.calendar.JDateChooser dataNascD;
    private javax.swing.JLabel dataNascL;
    private javax.swing.JButton excluirB;
    private javax.swing.JButton inclusaoB;
    private javax.swing.JButton limparU;
    private javax.swing.JButton listarB;
    private javax.swing.JTextField nomeD;
    private javax.swing.JLabel nomeL;
    private javax.swing.JTextField nomeMaeD;
    private javax.swing.JLabel nomeMaeL;
    private javax.swing.JTextField nomePaiD;
    private javax.swing.JLabel nomePaiL;
    private javax.swing.JTextArea observacaoD;
    private javax.swing.JLabel observacaoL;
    private javax.swing.JButton pesquisarB;
    private javax.swing.JFormattedTextField quantCriasD;
    private javax.swing.JLabel quantCriasL;
    private javax.swing.JTextField racaD;
    private javax.swing.JLabel racaL;
    private javax.swing.JButton salvarU;
    private javax.swing.JComboBox<String> sexoD;
    private javax.swing.JLabel sexoL;
    // End of variables declaration//GEN-END:variables
}
